name: deploy

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: install nix
        uses: cachix/install-nix-action@v30
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      - name: init cachix
        uses: cachix/cachix-action@v15
        with:
          name: mackeye-gha
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
          pushFilter: '(-source$)'

      - name: export direnv
        run: |
          mkdir -p "$HOME/.config/nix"
          printf "%s\n" "experimental-features = nix-command flakes" >> "$HOME/.config/nix/nix.conf"
          nix profile install nixpkgs#direnv
          direnv allow
          direnv export gha >> "$GITHUB_ENV"

      - name: make
        run: make

      - name: deploy
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: '${{secrets.CLOUDFLARE_API_TOKEN }}'
          accountId: '${{ secrets.CLOUDFLARE_ACCOUNT_ID }}'
          command: pages deploy --commit-dirty=true --project-name=homepage ./src/html
          gitHubToken: '${{ secrets.GITHUB_TOKEN }}'
